### ISSUE TITLE
Different result from statsmodels package

### ISSUE THREAD

**Issue by Kogia-sima** [FilippoBovo/robustats#5]
The following code shows the different result for medcouple.

```python
import robustats
from statsmodels.stats import stattools

data = [1., 2., 2., 2., 3., 4., 5., 6.]

mc = robustats.medcouple(data)
print(f'robustats: {mc}')

mc = stattools.medcouple(data)
print(f'stattools: {mc}')
```

Output:

```
robustats: 1.0
stattools: 0.5
```

My question is:

1. Why do the two methods return the different results?
2. Which result is theoretically correct?

**Comment by FilippoBovo** [comment]
Hi, @Kogia-sima.

Thanks for the questions.

To answer your first question, the two methods return different results because they use different definitions of the median inside the algorithm of the medcouple. There are three definitions of the median for an array, `a`, with an _even_ number of `n` elements:

- Lower median: `a[n/2 - 1]`
- Higher median: `a[n/2]`
- "Half-way" median: `(a[n/2 - 1] + a[n/2]) / 2`

The median in the `robustats` and `statstools` packages use different definitions.

To answer your second question, there is no right or wrong result, because the result depends on the definition of the median. Practically, the three definitions of the median that I gave above lead to very similar results, _unless_ we have small arrays, like the array that you used above, or arrays with many repeated values.

**Comment by Kogia-sima** [comment]
@FilippoBovo Oh, I understand. Thank you for your perfect explanation. Actually I didn't know that there are multiple definitions of median.

**Comment by FilippoBovo** [comment]
@Kogia-sima, I'm glad you found it helpful :)

**Comment by ctchervenkov** [comment]
Maybe you should let the user select which version they want to compute?

**Comment by FilippoBovo** [comment]
Yes, that’s an option. However, the difference between the two (actually, three) options is present only for small arrays with an even number of elements and depends on the way the weighted median is calculated. This is a library optimised to run on large arrays, where the difference is negligible. So, it makes little sense to allow for the choice of the option.

However, if you really need one of the three options, you *may* be able to get it like this,

```python
mc = (robustats.medcouple(data[1:]) + robustats.medcouple(data[:-1]))/2
```

Mind that I have not tested this, as I do not have my laptop with me. Please, let me know if it works.
